### ISSUE TITLE
It isn't 100% clear how the functional version of example 3 actually works

### ISSUE THREAD

**Issue by oliverjam** [Jwhiles/pure-functions-easy-testing#12]
It might be worth showing how exactly you would call the functions in Example 3. I know Zooey and I were quite confused about this until @Jwhiles explained it.

Maybe adding something like `updateDom(visionChange(changeTransition))()` at the end would demonstrate how this works. It could cause more confusion as it kind of jumps ahead into some functional programming stuff though.

Happy to do a PR if you think this would be an improvement.

**Comment by Jwhiles** [comment]
Please do so, your group were very much the guinea pigs for this :)

**Comment by oliverjam** [comment]
@Jwhiles Finally got around to doing this, only 4 months later. There's a PR with this and some other readme edits before FAC11 do this workshop :)

**Comment by Jwhiles** [comment]
slow and steady wins the race 🥇

**Comment by Jwhiles** [comment]
Let me know how it goes!!

**Comment by oliverjam** [comment]
Thanks, I will!
